title: CastlePeak's Homepage
page-top-title: Qingshan Li
top-section-bg-text: Be what you wanna be
home-subtitle: Qingshan Li&ensp;|&ensp;CastlePeak
copyright-text: '&copy; Qingshan Li 2025-2028. All Rights Reserved.'
